// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxTl_cCmvsANQ-hevnHTBhx0woSm6BLU',
    appId: '1:48413344846:web:e2b3aba4b3e53020cdaf1f',
    messagingSenderId: '48413344846',
    projectId: 'instamini-7e153',
    authDomain: 'instamini-7e153.firebaseapp.com',
    storageBucket: 'instamini-7e153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0LZahLJHBhXq8F0zyyK26X6zFdCE0xZ0',
    appId: '1:48413344846:ios:a2fc196789d77808cdaf1f',
    messagingSenderId: '48413344846',
    projectId: 'instamini-7e153',
    storageBucket: 'instamini-7e153.firebasestorage.app',
    iosBundleId: 'com.example.instaCloneMini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0LZahLJHBhXq8F0zyyK26X6zFdCE0xZ0',
    appId: '1:48413344846:ios:a2fc196789d77808cdaf1f',
    messagingSenderId: '48413344846',
    projectId: 'instamini-7e153',
    storageBucket: 'instamini-7e153.firebasestorage.app',
    iosBundleId: 'com.example.instaCloneMini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtxTl_cCmvsANQ-hevnHTBhx0woSm6BLU',
    appId: '1:48413344846:web:c4ac64fdaa99a7efcdaf1f',
    messagingSenderId: '48413344846',
    projectId: 'instamini-7e153',
    authDomain: 'instamini-7e153.firebaseapp.com',
    storageBucket: 'instamini-7e153.firebasestorage.app',
  );
}
